In [53]:
from bs4 import BeautifulSoup
import requests

In [54]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

headers = {
    "User-Agent": "SergioDataLearning/1.0 (educational web scraping project)"
}

page = requests.get(url, headers=headers)

print(page.status_code)

soup = BeautifulSoup(page.text, 'html.parser')

200

In [55]:
#print(soup)

In [56]:
#soup.find('table')

In [57]:
#soup.find_all('table')[1]

In [58]:
#soup.find('table', class_ = 'wikitable sortable')

In [59]:
table = soup.find_all('table')[0]

In [60]:
#print(table)

In [61]:
world_titles = table.find_all('th')

In [62]:
world_titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD millions)
 </th>,
 <th>Revenue growth
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [63]:
world_table_titles = [title.text.strip() for title in world_titles]
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [64]:
import pandas as pd

In [65]:
df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [66]:
column_data = table.find_all('tr')

In [67]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [68]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

In [69]:
df.to_csv(r'C:\Users\Sergio\Desktop\practice_da\web_scraping\largest_us_companies_by_revenue.csv', index = False)